service: aws-python
provider:
  name: aws
  runtime: python2.7
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - dynamodb:*
      Resource: "*"

functions:
  test-read-s3:
    handler: handler.lambda_handler
    events:
      - s3: # in this case, instead of http call, s3 will trigger the event to invoke our lambda function
          bucket: input-csv
          event: s3:ObjectCreated:* # the hello function will be invoked automatically upon file uploaded
          rules:
            - suffix: .csv
